# Generated by Django 3.0.6 on 2020-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='ad_images'),
        ),
    ]
