# Generated by Django 3.0.6 on 2020-06-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200620_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='ad_images'),
        ),
    ]
