# Generated by Django 3.0.6 on 2020-06-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200620_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='ad_images/default.png', upload_to='ad_images'),
        ),
    ]
