# Generated by Django 3.0.6 on 2020-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20200729_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='thumbnail',
            field=models.ImageField(default='ad_thumbnails/default.png', upload_to='ad_thumbnails'),
        ),
    ]
