# Generated by Django 3.0.6 on 2020-07-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20200721_0509'),
        ('private_messages', '0002_remove_privatemessage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ads.Ad'),
            preserve_default=False,
        ),
    ]
