# Generated by Django 3.0.6 on 2020-07-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0003_privatemessage_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver',
        ),
    ]
