# Generated by Django 3.0.6 on 2020-07-30 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20200729_1250'),
        ('private_messages', '0004_remove_privatemessage_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Ad')),
            ],
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='private_messages.Conversation'),
        ),
    ]
