# Generated by Django 3.0.6 on 2020-07-30 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_messages', '0005_auto_20200730_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter', to=settings.AUTH_USER_MODEL),
        ),
    ]
