# Generated by Django 3.0.6 on 2020-07-31 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_messages', '0007_conversation_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='ad',
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
