# Generated by Django 3.0.6 on 2020-07-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0008_auto_20200731_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver',
        ),
    ]
